Update terraform.yml

diff --git a/.github/workflows/terraform.yml b/.github/workflows/terraform.yml
--- a/.github/workflows/terraform.yml
+++ b/.github/workflows/terraform.yml
@@ -102,8 +102,8 @@ jobs:
 
     - name: terraform plan
       id: plan
-      run: terraform plan -no-color -out=terraform.plan -var 'project_id=${{ env.PROJECT_ID }}' -var 'env=${{ env.ENV }}'
-      continue-on-error: true
+      run: terraform plan -no-color -out=terraform.plan -var 'project_id=x' -var 'env=${{ env.ENV }}'
+ #     continue-on-error: true
     
    # - name: terraform show
    #   run: terraform show terraform.plan > plan.txt
@@ -162,9 +162,9 @@ jobs:
              body: output
           })
 
-    - name: terraform plan status
-      if: steps.plan.outcome == 'failure'
-      run: exit 1
+#    - name: terraform plan status
+#      if: steps.plan.outcome == 'failure'
+#      run: exit 1
        
     - name: terraform apply
       if: github.event_name == 'push'
